context:
  name: altair-aitools-runtime
  version: 1.1rc2
  python_min: 3.10.18

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://maven.rapidminer.com/repository/pypi-snapshot/packages/altair-aitools-runtime/${{ version }}/altair_aitools_runtime-${{ version }}.tar.gz
  sha256: ce99df399cb70a37fb61b2da4e89f529c2a84c39e297f9f800f15ff77119b413

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
  - python ==${{ python_min }}
  - hatchling
  - pip
  run:
  - python >=${{ python_min }}
  - numpy >=1.24
  - packaging >=24.1
  - pandas >=2.0.0
  - pydantic >=2.0.0
  - rapidminer >=2024.1.0
  - websockets >=12.0,<14

tests:
  - python:
      imports:
        - altair_aitools.ext
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: altair-aitools-runtime is a comprehensive package that provides a set of tools to run Altair RapidMiner AI tools extensions in Python.
  license: AGPL-3.0-only
  license_file: LICENSE
  homepage: https://altair.com/altair-rapidminer

extra:
  recipe-maintainers:
    - skontar-altair
    - pczako-altair
